[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = "lambdalisue/vim-pyenv"
on_ft = ['python']

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = "Flake8-vim"
on_ft = ['python']

[[plugins]]
repo = "hynek/vim-python-pep8-indent"
on_ft = ['python']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = ['go']

# go get -u github.com/cweill/gotests/...
[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = ['go']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'suan/vim-instant-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html']

[[plugins]]
repo = 'mattn/webapi-vim'
on_ft = ['css', 'html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'html']

[[plugins]]
repo = 'taichouchou2/html5.vim'
on_ft = ['css', 'html']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['css', 'html', 'javascript']

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'
on_ft = ['typescript']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['javascript', 'typescript', 'html', 'css']

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['javascript', 'javascript.jsx', 'html']

[[plugins]]
repo = 'clausreinke/typescript-tools'
on_ft = ['typescript']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
